DROP DATABASE IF EXISTS [bbab];
CREATE DATABASE [bbab];

CREATE TABLE [bbab].[dbo].[Principal](
	[PRINCIPAL_ID] INT NOT NULL IDENTITY(1,1),
	[FULL_NAME] NVARCHAR(50) NOT NULL,
	[USER_NAME] NVARCHAR(100) NOT NULL,
	[EMAIL] NVARCHAR(100) NOT NULL,
	[EMAIL_CONFIRMED] BIT DEFAULT 0,
	[PHONE_NUMBER] NVARCHAR(10) NOT NULL,
	[SALT] NVARCHAR(64) NOT NULL,
	[PASSWORD] NVARCHAR(64) NOT NULL,
	CONSTRAINT PK_principal PRIMARY KEY CLUSTERED (PRINCIPAL_ID));

CREATE TABLE [bbab].[dbo].[Address](
	[ADDRESS_ID] INT NOT NULL IDENTITY(1,1),
	[ADDRESS_1] NVARCHAR(100) NOT NULL,
	[ADDRESS_2] NVARCHAR(50),
	[ADDRESS_3] NVARCHAR(50),
	[CITY] NVARCHAR(30),
	[STATE] NVARCHAR(50),
	[COUNTRY] NVARCHAR(60),
	[ZIP] NVARCHAR(5),
	[PRINCIPAL_ID] INT NOT NULL,
	CONSTRAINT PK_address PRIMARY KEY CLUSTERED (ADDRESS_ID));

CREATE TABLE [bbab].[dbo].[Invoice](
	[INVOICE_ID] INT NOT NULL IDENTITY(1,1),
	[PRINCIPAL_ID] INT NOT NULL,
	[ADDRESS_ID] INT NOT NULL,
	[PRICE] FLOAT NOT NULL,
	[DATE] DATE DEFAULT GETDATE(),
	CONSTRAINT PK_invoice PRIMARY KEY CLUSTERED (INVOICE_ID));

CREATE TABLE [bbab].[dbo].[InvoiceContent](
	[INVOICE_CONTENT_ID] INT NOT NULL IDENTITY(1,1),
	[WEAPON_ID] INT NOT NULL,
	[INVOICE_ID] INT NOT NULL,
	CONSTRAINT PK_invoice_content PRIMARY KEY CLUSTERED (INVOICE_CONTENT_ID));

CREATE TABLE [bbab].[dbo].[Weapon](
	[WEAPON_ID] INT NOT NULL IDENTITY(1,1),
	[MAKE] NVARCHAR(50) NOT NULL,
	[MODEL] NVARCHAR(50) NOT NULL,
	[CALIBER] NVARCHAR(10) NOT NULL,
	[SERIAL_NUMBER] NVARCHAR(25) NOT NULL,
	[PRICE] FLOAT NOT NULL,
	CONSTRAINT PK_weapon PRIMARY KEY CLUSTERED (WEAPON_ID));

CREATE TABLE [bbab].[dbo].[Cart](
	[CART_ID] INT NOT NULL IDENTITY(1,1),
	[PRINCIPAL_ID] INT NOT NULL,
	[WEAPON_ID] INT NOT NULL,
	CONSTRAINT PK_cart PRIMARY KEY CLUSTERED (CART_ID));

CREATE TABLE [bbab].[dbo].[Admin](
	[ADMIN_ID] INT NOT NULL IDENTITY(1,1),
	[LEVEL] INT NOT NULL,
	[TITLE] NVARCHAR(20) NOT NULL,
	[PRINCIPAL_ID] INT,
	CONSTRAINT PK_admin PRIMARY KEY CLUSTERED (ADMIN_ID));

ALTER TABLE [bbab].[dbo].[Admin]
	ADD CONSTRAINT FK_admin_principal FOREIGN KEY (PRINCIPAL_ID)
	REFERENCES [bbab].[dbo].[Principal] (PRINCIPAL_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE [bbab].[dbo].[Address]
	ADD CONSTRAINT FK_address_principal FOREIGN KEY (PRINCIPAL_ID)
	REFERENCES [bbab].[dbo].[Principal] (PRINCIPAL_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE [bbab].[dbo].[Invoice]
	ADD CONSTRAINT FK_invoice_address FOREIGN KEY (ADDRESS_ID)
	REFERENCES [bbab].[dbo].[Address] (ADDRESS_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE [bbab].[dbo].[Invoice]
	ADD CONSTRAINT FK_invoice_principal FOREIGN KEY (PRINCIPAL_ID)
	REFERENCES [bbab].[dbo].[Principal] (PRINCIPAL_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE [bbab].[dbo].[InvoiceContent]
	ADD CONSTRAINT FK_invoicecontent_weapon FOREIGN KEY (WEAPON_ID)
	REFERENCES [bbab].[dbo].[Weapon] (WEAPON_ID)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE [bbab].[dbo].[InvoiceContent]
	ADD CONSTRAINT FK_invoicecontent_invoice FOREIGN KEY (INVOICE_ID)
	REFERENCES [bbab].[dbo].[Invoice] (INVOICE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE [bbab].[dbo].[Cart]
	ADD CONSTRAINT FK_cart_weapon FOREIGN KEY (WEAPON_ID)
	REFERENCES [bbab].[dbo].[Weapon] (WEAPON_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE [bbab].[dbo].[Cart]
	ADD CONSTRAINT FK_cart_principal FOREIGN KEY (PRINCIPAL_ID)
	REFERENCES [bbab].[dbo].[Principal] (PRINCIPAL_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

INSERT INTO [bbab].[dbo].[admin] ([LEVEL], [TITLE]) VALUES (1, 'HumanResource');
INSERT INTO [bbab].[dbo].[admin] ([LEVEL], [TITLE]) VALUES (1, 'InventoryManager');
INSERT INTO [bbab].[dbo].[admin] ([LEVEL], [TITLE]) VALUES (2, 'Admin');